### PR TITLE
Update nl.yml

### PR DESCRIPTION
**Pull request by yveshanoulle**
I translated all short text, I will translate the larger text all in separate updates...

### CODE REVIEW

**Review by peterarmstrong — APPROVED** [review]
Thanks Yves!

**Comment by yveshanoulle** [comment]
> Thanks Yves!

Is this now automagically used for the next generation of books?

**Comment by peterarmstrong** [comment]
I still need to merge it into Leanpub and then it will go out on the next deploy, either this week or early next week. I was going to reply to your email once it was live...

**Comment by peterarmstrong** [comment]
(But yeah, once it's deployed, it's used for everything.)

**Comment by peterarmstrong** [comment]
This is live now; thanks again...

**Pull request merged**
